//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "album")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub title: String,
    pub r#type: String,
    pub release_date: DateTime,
    pub image: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::recent_track::Entity")]
    RecentTrack,
}

impl Related<super::recent_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RecentTrack.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
