//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::account::Entity as Account;
pub use super::album::Entity as Album;
pub use super::album_artist::Entity as AlbumArtist;
pub use super::album_track::Entity as AlbumTrack;
pub use super::artist::Entity as Artist;
pub use super::play_log::Entity as PlayLog;
pub use super::track::Entity as Track;
pub use super::user::Entity as User;
